#ifndef MAINWINDOW_HH
#define MAINWINDOW_HH

#include <QMainWindow>
#include "gradecalculator.hh"

QT_BEGIN_NAMESPACE //preprocessor directives
namespace Ui
{
    class MainWindow;
}
QT_END_NAMESPACE //preprocessor directives

class MainWindow : public QMainWindow
{
    Q_OBJECT //macro

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void on_calculatePushButton_clicked();

private:
    Ui::MainWindow *ui; //Ui::MainWindow is a
    //class generated by the Qt
    //here is the pointer
};
#endif // MAINWINDOW_HH

/*
 * preprocessor directives are instructions that are
 * preprocessed by the preprocessor before the actual
 * compilation process begin.
 *
 * used to include or exclude code based on certain
 * conditions or to define certain constraints
 *
 * macros: code snippets that are replaced by the
 * preprocessor before the actual compilation process begin
 *
 * simpliy the code and make it easier to read and write
 * Q object o day dung de generate code ma support
 * advanced features nhu la signals and slots
 */
